#version: '3'
#services:
 # app:
 #   image: node:16
#    context: .
  #  container_name: NodeApp
   # restart: always
   # ports:
    #  - "9000:9000"


version: '3.3'

services:
  nodeapp:
    container_name: NodeApp
    image: node:16
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: bash -c "node index.js"
    restart: always

